package com.example.demo.exception;

import java.time.LocalDateTime;

import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

@RestControllerAdvice
public class GlobalExceptionHandler {

	@ExceptionHandler(InvalidContactException.class)
    public ErrorResponse handleInvalidEmployeeException(InvalidContactException ex) {
        // You can create a new instance of ErrorResponse with the error details
        return new ErrorResponse(
                null, // `id` could be autogenerated if needed, or set as null
                "INVALID_EMPLOYEE"
                
        );
    }
}
